name: Deploy to EC2 with Maven

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean package  # 이 명령어는 WAR 파일을 생성합니다

      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/ec2.pem
          chmod 600 ~/ec2.pem
          
      - name: make dir .ssh
        run: |
          mkdir -p ~/.ssh

      - name: Add known hosts
        run: |
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy WAR to EC2
        run: |
          ssh -i ~/ec2.pem -o UserKnownHostsFile=~/.ssh/known_hosts -tt ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "rm -f /opt/tomcat/apache-tomcat-9.0.95/webapps/ROOT.war"  # 기존 파일 삭제
          scp -o StrictHostKeyChecking=no target/ROOT.war ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:/opt/tomcat/apache-tomcat-9.0.95/webapps/
        env:
          SSH_PEM_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Restart Tomcat
        run: |
          ssh -i ~/ec2.pem -o UserKnownHostsFile=~/.ssh/known_hosts -tt ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "/opt/tomcat/apache-tomcat-9.0.95/bin/shutdown.sh"
          ssh -i ~/ec2.pem -o UserKnownHostsFile=~/.ssh/known_hosts -tt ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "/opt/tomcat/apache-tomcat-9.0.95/bin/startup.sh"
